/**
 * Import the 69 verbatim articles extracted from jamiat.joburg into the
 * database, REPLACING the current placeholder articles entirely.
 *
 * Source: /home/z/my-project/scripts/fetched/extracted_articles.json
 *         (generated by scripts/extract_articles.py from upload/manifest.json)
 *
 * Run: bun run scripts/import_articles.ts
 */
import { PrismaClient } from '@prisma/client';
import { readFileSync } from 'fs';

const db = new PrismaClient();

interface ExtractedArticle {
  title: string;
  cat: string;
  catLabel: string;
  date: string;
  excerpt: string;
  body: string;
  url: string;
}

async function main() {
  const raw = readFileSync('/home/z/my-project/scripts/fetched/extracted_articles.json', 'utf-8');
  const articles: ExtractedArticle[] = JSON.parse(raw);

  console.log(`Loaded ${articles.length} extracted articles from manifest.`);

  // Wipe existing articles
  const deleted = await db.article.deleteMany({});
  console.log(`Deleted ${deleted.count} existing articles.`);

  // Insert the verbatim articles
  let inserted = 0;
  for (const a of articles) {
    // Skip articles with no meaningful body
    if (!a.body || a.body.trim().length < 50) {
      console.log(`  ⚠ SKIP (body too short): ${a.title.slice(0, 60)}`);
      continue;
    }
    await db.article.create({
      data: {
        title: a.title,
        cat: a.cat,
        catLabel: a.catLabel,
        date: a.date || '—',
        excerpt: a.excerpt || a.body.slice(0, 280),
        body: a.body,
      },
    });
    inserted++;
  }

  console.log(`\nInserted ${inserted} verbatim articles.`);

  // Verify
  const count = await db.article.count();
  console.log(`Total articles in DB: ${count}`);

  // Category breakdown
  const cats = await db.article.groupBy({
    by: ['catLabel'],
    _count: { catLabel: true },
    orderBy: { _count: { catLabel: 'desc' } },
  });
  console.log('\nCategory breakdown:');
  for (const c of cats) {
    console.log(`  ${c.catLabel}: ${c._count.catLabel} articles`);
  }

  // Total body text
  const all = await db.article.findMany({ select: { body: true } });
  const totalChars = all.reduce((sum, a) => sum + a.body.length, 0);
  console.log(`\nTotal verbatim text: ${totalChars.toLocaleString()} chars (~${Math.round(totalChars / 6).toLocaleString()} words)`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
