/* Seed Jamiatul Ulama Johannesburg mini-database.
 * Run: bun run scripts/seed.ts
 */
import { PrismaClient } from '@prisma/client';

const db = new PrismaClient();

const FATWAS = [
  { q:"Is it permissible to pay Zakāh on behalf of a deceased person from his estate before distribution?",cat:"Zakāh",answer:"Yes, it is permissible. The fuqahā of the Ḥanafī school hold that Zakāh owed by the deceased is a debt upon his estate. It takes priority before distribution of the inheritance, provided the deceased made a bequest (waṣiyyah) for it or the heirs agree to pay it. It must be disbursed to eligible recipients directly.",source:"Fatāwā Hindiyyah, Vol. 1 · Al-Ikhtiyār, Mawṣilī" },
  { q:"What is the ruling on Ṣadaqah al-Fiṭr for a person who accepted Islam after the commencement of Ramaḍān?",cat:"Zakāh al-Fiṭr",answer:"If a person accepts Islam during Ramaḍān and possesses the Niṣāb at the time of Eid al-Fiṭr, Ṣadaqah al-Fiṭr becomes obligatory upon him. The obligation is linked to being Muslim at the time of Eid — not to having fasted the entire month.",source:"Al-Hidāyah, Margīnānī · Fatāwā Qāḍīkhān" },
  { q:"Does performing I'tikāf in a muṣallā not designated as a masjid fulfil the Sunnah requirement?",cat:"I'tikāf",answer:"The Ḥanafī position is that the Sunnah mu'akkadah of I'tikāf during the last ten nights of Ramaḍān is only valid in a masjid with regular congregational prayer (jamā'ah). A muṣallā that is not formally designated as a masjid would not fulfil this requirement. Nafl I'tikāf, however, is valid in any place set aside for prayer.",source:"Radd al-Muḥtār, Ibn 'Ābidīn · Baḥr al-Rā'iq" },
  { q:"Can a woman in ḥaiḍ recite du'ā from memory or handle the Qur'ān in a cover?",cat:"Ṭahārah",answer:"A woman in ḥaiḍ may recite du'ā and dhikr freely. As for Qur'ānic recitation, she may not recite verses with the intention of Qur'ān — though commonly-known supplicatory verses (e.g. Āyat al-Kursī as protection) are permitted. Handling the Muṣḥaf is not permissible without a cover creating a barrier.",source:"Fatāwā Hindiyyah · Marāqī al-Falāḥ" },
  { q:"What is the minimum Niṣāb for Zakāh in South African Rand for 1448 AH?",cat:"Zakāh",answer:"The Niṣāb of Zakāh equals 87.48 grams of gold or 612.35 grams of silver. As per the Jamiat's Financial Indicators (updated 22 June 2026), the Niṣāb in Rand stands at R22,136.44. Any Muslim possessing this amount (or equivalent assets) for a full lunar year must pay 2.5% as Zakāh.",source:"Jamiat Joburg Financial Indicators — Muḥarram 1448 AH" },
  { q:"Is Satr-e-Aurah broken by wearing tight jeans during Ṣalāh, even without exposure?",cat:"Ṣalāh",answer:"A Fardh condition for valid Ṣalāh is proper concealment of the satr — for a male, from the navel to the knees. This concealment requires that the shape of the private parts not be revealed, not merely that they be covered by cloth. Tight jeans, especially in sajdah, reveal the form of the satr-e-ghaleez. Such Ṣalāh is invalid and must be repeated in proper, looser Islamic attire.",source:"Radd al-Muḥtār · Al-Durr al-Mukhtār" },
  { q:"Is performing Ṣalāh seated on a chair valid for someone who is able to stand with difficulty?",cat:"Ṣalāh",answer:"A person who can stand, even with difficulty or support, is obligated to perform Ṣalāh standing. Sitting on a chair for Ṣalāh is only permitted for one who is genuinely unable to stand or perform rukū' and sajdah on the ground. Using a chair without genuine necessity invalidates the structure of the Ṣalāh.",source:"Fatāwā Maḥmūdiyyah · Al-Fiqh al-Ḥanafī" },
  { q:"Is it correct to walk in front of a person who is performing Ṣalāh?",cat:"Ṣalāh",answer:"It is a major sin to walk directly in front of a person engaged in Ṣalāh, between him and the place his gaze falls in sajdah (approximately three feet). The Prophet ﷺ warned in extremely strong terms against this. One should wait or go around if at all possible.",source:"Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim" },
  { q:"What du'ās should be recited when performing Qurbāni or 'Aqīqah?",cat:"Qurbāni",answer:"Before slaughter, one should recite Bismillāhi Allāhu Akbar, then the du'ā: Innī wajjahtu wajhiya... affirming sincerity to Allah, followed by Allāhumma minka wa laka (for Qurbāni) or with the name of the person on whose behalf 'Aqīqah is offered.",source:"Sunan Abī Dāwūd · Fiqh al-Ḥanafī manuals" },
  { q:"Is it permissible to give Zakāh or Lillah to an organisation whose practices are not verified as Sharī'ah-compliant?",cat:"Zakāh",answer:"Zakāh has strict conditions of valid disbursement — it must reach an eligible recipient (Mustahiq) directly or via an agent acting strictly on the donor's behalf. Where an organisation's structure, fundraising practices, or use of funds raises doubt as to Sharī'ah-compliance, it is not permissible to discharge one's Zakāh obligation through it, as the obligation may remain undischarged.",source:"Fatāwā Hindiyyah · Bahishti Zewar" },
  { q:"Are vaccinations always Ḥarām, or does the ruling depend on ingredients and necessity?",cat:"Fiqh",answer:"The default ruling on medical intervention, including vaccination, is permissibility, subject to genuine medical necessity and absence of an impermissible ingredient where an alternative exists. Where no Ḥarām ingredient is confirmed and there is medical necessity, vaccination is not impermissible. Each case should be assessed on its specific facts rather than blanket pronouncement.",source:"Qawāʿid al-Fiqhiyyah · Contemporary Fatāwā councils" },
  { q:"Is the so-called 'Mass Tahajjud' gathering, organised as a public spectacle, in line with the Sunnah?",cat:"Bid'ah",answer:"Tahajjud is an individual, night-time act of worship performed in privacy and sincerity. Organising it as a large public, publicised, mixed-gender spectacle changes its character and opens the door to riyā (showing off) and innovation in how an act of worship is presented. Such gatherings, as commonly organised, are not in keeping with the Sunnah manner of this 'ibādah.",source:"Iqtiḍā' al-Ṣirāṭ al-Mustaqīm · Classical Uṣūl works" },
];

const ARTICLES = [
  { title:"Understanding I'tikāf: The Complete Ḥanafī Guide",cat:"fiqh",catLabel:"Fiqh",date:"12 Dhul-Hijjah 1446",excerpt:"I'tikāf — the spiritual retreat within the masjid during the last ten nights of Ramaḍān — carries specific conditions and rulings. This guide covers definitions, obligations, conditions of validity, and what nullifies it.",body:"I'tikāf is a Sunnah mu'akkadah 'alal-kifāyah — if performed by even one person in a locality, the obligation is lifted from the rest. Its essential pillar (rukn) is staying (labth) in the masjid with the intention of I'tikāf.\n\nThe conditions of validity are: (1) Islam, (2) sanity, (3) intention, (4) to be in a masjid — and for the Sunnah I'tikāf of Ramaḍān, in a masjid where congregational Ṣalāh is held (jamā'ah). A muṣallā not formally designated as a masjid does not fulfil this.\n\nAmong the things that nullify I'tikāf: leaving the masjid without a valid Shar'ī reason (e.g. wudhu, eating if no food can be brought inside, or a genuine necessity), marital relations, and apostasy. Leaving for a valid reason must be only for the necessary duration.\n\nThe Sunnah period is the last ten nights of Ramaḍān, entering the masjid before sunset on the 20th night and remaining until the moon of Eid is sighted.\n\nIt is recommended to increase in recitation of the Qur'ān, dhikr, and du'ā, and to avoid vain talk. The one in I'tikāf may eat, drink, and sleep inside the masjid, taking care to maintain its sanctity.\n\nSources: Radd al-Muḥtār · Al-Hidāyah · Baḥr al-Rā'iq · Fatāwā Hindiyyah" },
  { title:"Distractions During Ṣalāh: What Affects the Validity?",cat:"salah",catLabel:"Ṣalāh",date:"10 Dhul-Hijjah 1446",excerpt:"A careful examination of the conditions that render prayer void (bāṭil) versus those which are merely disliked (makrūh), with practical guidance for common scenarios.",body:"Ṣalāh is invalidated by: (1) anything that breaks wudū — speech (even two letters), eating, drinking, excessive laughter, loss of consciousness; (2) turning the chest away from the qiblah; (3) excessive movement; (4) exposure of the satr for the duration of a rukn; (5) utterance of 'Salam' deliberately without reason; (6) impurity appearing on body or cloth.\n\nMakrūh (disliked but valid) actions include: fidgeting, looking around, cracking knuckles, attending to worldly need. These reduce reward but do not invalidate.\n\nCommon scenarios: a phone ringing does not invalidate if ignored; brief crying does not invalidate; a child climbing on the back of the one praying does not invalidate. The principle: minor movements that do not depart from the form of Ṣalāh are makrūh; major movements that change the outward shape of Ṣalāh invalidate.\n\nSource: Al-Hidāyah · Radd al-Muḥtār" },
  { title:"Zakāh on Business Inventory: A Practical Calculation Guide",cat:"zakah",catLabel:"Zakāh",date:"8 Dhul-Hijjah 1446",excerpt:"How to correctly value stock-in-trade, outstanding receivables, and cash holdings when computing Zakāh at the Niṣāb threshold for business owners.",body:"Zakāh on business inventory is obligatory on stock held for trade. The calculation: value all trade stock at current market selling price on the Zakāh anniversary date. Add cash on hand and at bank, plus outstanding receivables you reasonably expect to recover. Subtract current liabilities (debts payable within the year). Multiply the total by 2.5%.\n\nStock-in-trade means goods held for resale. Tools and equipment used in the business (machinery, vehicles, computers) are not Zakāh-able. Personal assets (your home, car for personal use, furniture) are not Zakāh-able.\n\nReceivables: there are two positions. The relied-upon (muftā-bih) Ḥanafī position is that receivables are included at full value, but Zakāh is paid the year they are received, for all past years. The alternative (Ibn 'Ābidīn) is to include at expected realisable value. Consult a scholar for your specific case.\n\nLoss assets (bad debts you have written off) are not included.\n\nSource: Fatāwā Hindiyyah · Fatāwā Raḥīmiyyah · Bahishti Zewar" },
  { title:"Qurbāni Rulings: Animals, Shares & the Correct Procedure",cat:"fiqh",catLabel:"Fiqh",date:"3 Dhul-Hijjah 1446",excerpt:"The essential rulings on which animals qualify for Qurbāni, the permissibility of sharing in a large animal, and the recommended method of slaughter.",body:"Qurbāni is Wājib upon every adult, sane Muslim who possesses the Niṣāb on the days of Qurbāni (10th, 11th, 12th Dhul-Hijjah) after deducting basic needs and debts.\n\nEligible animals: camel (5 years), cow/ox/buffalo (2 years), goat/sheep (1 year, or 6 months if it is so fat it appears one year). Defects that disqualify: blindness, obvious lameness, missing a third or more of an ear or tail, missing a major limb, emaciation, missing more than one-third of the tongue.\n\nShares: a camel = 7 shares; a cow = 7 shares; a goat/sheep = 1 share. Multiple people may share a large animal, but each person's intention must be Qurbāni (not meat-procurement).\n\nMethod: face the qiblah; sharpen the blade; recite Bismillāhi Allāhu Akbar; cut the trachea, oesophagus, and both jugular veins. The animal must not be skinned or moved until fully cold.\n\nDistribution: one-third for self, one-third for family/friends, one-third for the poor — this is Sunnah but not obligatory. All meat may be given away if one wishes.\n\nSource: Sunan Abī Dāwūd · Ṣaḥīḥ al-Bukhārī · Fatāwā Hindiyyah" },
  { title:"The Shar'ī Requirements of Islamic Dress for Men & Women",cat:"fiqh",catLabel:"Fiqh",date:"28 Dhul-Qa'dah 1446",excerpt:"A balanced, sourced treatment of 'awrah, covering requirements, and the distinction between obligatory requirements and recommended practice.",body:"The satr (must-be-covered) for a man is from the navel to below the knees — the knees themselves must be covered. For a free woman in front of non-mahram, the entire body except the face and hands (according to the relied-upon Ḥanafī position). The clothing must: (1) not be so tight it reveals the form of the satr; (2) not be so transparent the skin colour shows; (3) not itself be a garment resembling the opposite sex; (4) not itself resemble the religious dress of other communities (tashabbuh).\n\nThe Prophet ﷺ cursed men who imitate women and women who imitate men. Likewise, he ﷺ cursed those who imitate a people, becoming one of them. These principles frame additional guidance beyond mere coverage.\n\nRecommended (mustahabb) aspects: white clothing, modest in cut, clean, not ostentatious. For men, the Sunnah length is to mid-calf (the izar); below the ankle is makrūh tanzīh in the Ḥanafī school.\n\nSource: Ṣaḥīḥ al-Bukhārī · Sunan Abī Dāwūd · Radd al-Muḥtār" },
  { title:"Salāt Is Not Valid! — The Satr Requirement and Modern Dress",cat:"salah",catLabel:"Ṣalāh",date:"21 Dhul-Qa'dah 1446",excerpt:"A Fardh condition for valid Ṣalāh is proper concealment of the satr. Why tight, kuffār-style jeans and T-shirts render Ṣalāh in the Musjid invalid, and what proper Islamic attire requires.",body:"Ṣalāh has conditions of validity (shurūṭ) that must be met before takbīr al-taḥrīmah. One of these is the concealment of the satr — for the male, from the navel to (and including) the knees. This concealment requires that the form of the satr-e-ghaleez not be revealed, not merely that the area be covered by cloth.\n\nTight jeans — especially in the sajdah posture — reveal the form of the satr, breaking the condition of concealment. Such Ṣalāh is invalid and must be repeated in proper, looser Islamic attire. The same applies to tight shorts that ride above the knee in rukū' or sajdah.\n\nLoose trousers that cover below the knees with room to spare are acceptable, provided they do not resemble kuffār-style dress. The Sunnah attire — a loose izar/lungi and qamīṣ — is the most complete answer.\n\nSource: Radd al-Muḥtār · Al-Durr al-Mukhtār" },
  { title:"Performing Ṣalāh on a Chair — When Is It Actually Permitted?",cat:"salah",catLabel:"Ṣalāh",date:"19 Dhul-Qa'dah 1446",excerpt:"Sitting for Ṣalāh is a concession for genuine inability to stand, not a matter of comfort. A clear explanation of when this concession applies and when it does not.",body:"The default of Ṣalāh is standing (qiyām) — it is a rukn (pillar) for the Fardh of one who is able. The concession to sit applies only when standing is genuinely impossible or would cause significant harm (e.g. genuine illness, old age, injury, recent surgery).\n\nThe one who can stand but with difficulty should still stand. The one who cannot stand at all may sit on the floor for Ṣalāh, performing rukū' and sajdah by gesture. The one who cannot sit on the floor may sit on a chair, gesturing for rukū' and sajdah by slightly lowering the head.\n\nUsing a chair without genuine necessity invalidates the structure of the Ṣalāh. The Hanafī Fuqahā have explicitly cautioned against this as an emerging practice that nullifies the prayer.\n\nSource: Al-Hidāyah · Fatāwā Maḥmūdiyyah · Radd al-Muḥtār" },
  { title:"The Sin of Walking in Front of Another Performing Ṣalāh",cat:"salah",catLabel:"Ṣalāh",date:"15 Dhul-Qa'dah 1446",excerpt:"Why walking directly in front of someone praying carries such severe warning in the Sunnah, and the etiquette of passing through a Musjid during congregational prayer.",body:"The Prophet ﷺ said: 'If the one passing in front of a praying person knew what was upon him, he would prefer to stand forty (years/months) rather than pass in front of him.' (Ṣaḥīḥ al-Bukhārī & Muslim)\n\nThe prohibited area is between the praying person and his place of sajdah — approximately three feet (one dhirā') from where his forehead touches the ground. To pass within this area is a major sin.\n\nThe etiquette: wait if the person is in Ṣalāh. If you must move, go around behind the rows. The one praying may set up a sutrah (a barrier — wall, stick, etc.) before takbīr al-taḥrīmah, in which case passing between him and the sutrah is prohibited.\n\nIf the masjid is full and movement is unavoidable, the person praying should not be disrupted. Make du'ā for forgiveness rather than cause further harm.\n\nSource: Ṣaḥīḥ al-Bukhārī · Ṣaḥīḥ Muslim · Sunan Abī Dāwūd" },
  { title:"Bukhārī Sharīf Recitation Gatherings — Yet Another Bid'ah in the Making",cat:"bidah",catLabel:"Bid'ah",date:"12 Dhul-Qa'dah 1446",excerpt:"An examination of newly-invented communal 'Bukhārī Sharīf recitation' ceremonies that have no basis in the practice of the Ṣaḥābah or the classical 'Ulamā.",body:"The Ṣaḥābah رضي الله عنهم and the Salaf al-Ṣāliḥīn studied Ḥadīth for the purpose of acting upon it — reciting, memorising, understanding, and implementing. There is no recorded practice of the Ṣaḥābah or the Imāms of gathering specifically to 'recite' a Ḥadīth collection as a communal ceremony, with the goal of blessing alone.\n\nThe recent practice of 'Bukhārī Sharīf khatam' — gathering to ceremonially read through Ṣaḥīḥ al-Bukhārī in a fixed period, with food, flowers, and publicised 'closing' ceremonies — has no basis in the Sunnah. While reading Ḥadīth is meritorious, turning it into a religious rite with the trappings of a formal 'ibādah is an innovation (bid'ah).\n\nThe Prophet ﷺ said: 'Whoever introduces into this affair of ours that which is not from it, it is rejected.' (Ṣaḥīḥ al-Bukhārī & Muslim)\n\nWe urge the community to return to the classical method: study Ḥadīth under qualified 'Ulamā, with the intention of acting upon it.\n\nSource: Iqtiḍā' al-Ṣirāṭ al-Mustaqīm · Fatāwā Rashīdiyyah" },
  { title:"Using the Miswāk Immediately Before Ṣalāh — Dispelling a Misconception",cat:"fiqh",catLabel:"Fiqh",date:"9 Dhul-Qa'dah 1446",excerpt:"Clarifying a common misunderstanding regarding the timing and manner of using the miswāk in relation to the commencement of Ṣalāh.",body:"The miswāk is a Sunnah of wudū — to be used during the rinsing of the mouth — and a Sunnah before every Ṣalāh. The Prophet ﷺ said: 'Were it not that I would cause hardship to my Ummah, I would have ordered the miswāk with every Ṣalāh.' (Ṣaḥīḥ al-Bukhārī & Muslim)\n\nSome have erroneously held that using the miswāk immediately before takbīr is makrūh or otherwise inappropriate. This is incorrect. The Sunnah is to use the miswāk, then proceed directly to Ṣalāh. There is no dalālah in the Sunnah to discourage this.\n\nThe recommended time is just before wudū (during mouth-rinsing) and again before each Ṣalāh. The miswāk is also recommended upon entering the home, upon waking, and when the mouth has an unpleasant smell.\n\nSource: Ṣaḥīḥ al-Bukhārī · Sunan Abī Dāwūd · Marāqī al-Falāḥ" },
  { title:"What's Good for the Goose… — A Look at Selective Outrage",cat:"akhlaq",catLabel:"Akhlāq",date:"5 Dhul-Qa'dah 1446",excerpt:"A reflection on consistency in applying Islamic principles, rather than selective application based on convenience or political alignment.",body:"A believer's standard is the Sharī'ah — not political alignment, personal sympathy, or tribal loyalty. When we apply a ruling strictly to those we oppose and overlook the same ruling for those we favour, we have departed from adl (justice).\n\nAllah says: 'And let not the hatred of a people prevent you from being just. Be just; that is nearer to righteousness.' (Sūrah al-Mā'idah 5:8)\n\nThe believer examines every issue on its merits — the act, the doer, the Shar'ī ruling. Selective outrage — where we condemn in our opponents what we excuse in our allies — is a spiritual disease. It erodes our own integrity and the credibility of our Da'wah.\n\nThe Sunnah calls us to a consistent, principled position. May Allah grant us this quality." },
  { title:"Allah Ta'ālā Becomes Angry, and His 'Arsh Shakes, When a Fāsiq Is Praised",cat:"akhlaq",catLabel:"Akhlāq",date:"1 Dhul-Qa'dah 1446",excerpt:"On the severity of publicly praising open sinners and transgressors, and the responsibility of the community in how it elevates public figures.",body:"The Prophet ﷺ said: 'When a fāsiq is praised, the 'Arsh of Allah trembles; the angels of the heavens become angry; and Allah becomes angry.' ( Reported in Ṭabarānī, al-Mu'jam al-Awsaṭ; al-Mundhirī in al-Targhīb; chain assessed as ḥasan by some scholars)\n\nThe gravity of this is that praising an open sinner — beyond the limits Sharī'ah permits — draws the anger of Allah. The community has a duty to be discerning in who it elevates. Public platforms, awards, and honours carry a Shar'ī weight.\n\nThis does not preclude recognizing worldly skill (e.g. a non-Muslim doctor's medical expertise). It refers to elevating someone whose transgression is known, in a manner that emboldens their sin.\n\nMay Allah protect us from being among those who normalise the Ḥarām." },
  { title:"Du'ās to Be Recited When Making Qurbāni and 'Aqīqah",cat:"fiqh",catLabel:"Fiqh",date:"26 Shawwāl 1446",excerpt:"The specific supplications to recite at the time of slaughter for Qurbāni and 'Aqīqah, with their sourcing from the Sunnah.",body:"Before slaughter, recite:\n\nبِسْمِ اللهِ، اللهُ أَكْبَر\n'Bismillāhi Allāhu Akbar.'\n\nFor Qurbāni, recite the following du'ā (after Bismillah and takbīr):\n\nاللَّهُمَّ مِنْكَ وَلَكَ\n'Allāhumma minka wa laka.'\n\nAnd:\n\nإِنِّي وَجَّهْتُ وَجْهِيَ لِلَّذِي فَطَرَ السَّمَاوَاتِ وَالأَرْضَ حَنِيفًا وَمَا أَنَا مِنَ الْمُشْرِكِينَ، إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ رَبِّ الْعَالَمِينَ، لاَ شَرِيكَ لَهُ وَبِذَلِكَ أُمِرْتُ وَأَنَا مِنَ الْمُسْلِمِينَ\n'Innī wajjahtu wajhiya lilladhī faṭaras-samāwāti wal-arḍa ḥanīfan wa mā ana minal-mushrikīn. Inna ṣalātī wa nusukī wa maḥyāya wa mamātī lillāhi rabbil-'ālamīn, lā sharīka lah, wa bidhālika umirtu wa ana minal-muslimīn.'\n\nFor Qurbāni on behalf of another, add: 'Allāhumma taqabbal min [name]'. For 'Aqīqah, add the name of the child on whose behalf it is offered.\n\nSource: Sunan Abī Dāwūd · Ṣaḥīḥ Muslim · Sunan Ibn Mājah" },
  { title:"A Vote for a Political Party That Embraces Kufr Is a Vote for Kufr",cat:"akhlaq",catLabel:"Akhlāq",date:"20 Shawwāl 1446",excerpt:"A position paper on the impermissibility of supporting political movements whose platforms openly contradict fundamental tenets of Islamic belief.",body:"Voting in a democratic election, where the voter chooses a representative, is in principle permissible — provided the platform of the chosen party does not contain open kufr or facilitate the spread of kufr.\n\nWhere a party's platform openly contradicts a fundamental tenet of Islām — for example, by legislating what Allah has forbidden or forbidding what Allah has legislated, in a manner that constitutes open kufr — then voting for that party, knowing of its stance, falls under the same ruling.\n\nThe Muslim voter must exercise due diligence. Not every party that is unsavoury reaches the level of kufr; but where it does, the ruling is severe. Where it does not, the Muslim voter weighs the lesser of available harms (aqall al-ḍararayn) — but this principle does not apply where one of the options is open kufr.\n\nThis is the stated position of the Jamiat and of the major Ḥanafī Fatāwā councils of South Africa.\n\nSource: Fatāwā of contemporary Ḥanafī councils · Sharḥ al-'Aqīdah al-Ṭaḥāwiyyah" },
  { title:"It Is Not Permissible to Give Lillah or Zakāt to Organisations Without Verified Sharī'ah Compliance",cat:"zakah",catLabel:"Zakāh",date:"14 Shawwāl 1446",excerpt:"Donors bear responsibility to verify that charitable organisations meet the conditions for valid Zakāh disbursement before contributing.",body:"Zakāh is a Fardh 'ibādah — a worship with strict Shar'ī conditions for valid discharge. It must reach an eligible recipient (Mustahiq) directly, or via an agent (wakīl) acting strictly on the donor's behalf, with full taḥarrī (verification) and tamlīk (transfer of ownership).\n\nLillah is a nafl charity that does not require the same strict conditions, but is still subject to the principle of not facilitating sin.\n\nWhere an organisation's structure, fundraising practices, mixed-funds accounting, or use of funds raises doubt as to Sharī'ah-compliance — for example, by combining Zakāh and Lillah in a single account without separation, or by directing funds to recipients who may not be Mustahiq — it is not permissible to discharge one's Zakāh obligation through it. The obligation may remain undischarged, and the donor remains liable.\n\nDonors bear a Shar'ī responsibility to verify. Asking a few questions of the organisation's administrators is the minimum.\n\nSource: Fatāwā Hindiyyah · Bahishti Zewar · Fatāwā Maḥmūdiyyah" },
  { title:"Paying the Youth to Attend Fardh Ṣalāh — A Critical Look",cat:"akhlaq",catLabel:"Akhlāq",date:"8 Shawwāl 1446",excerpt:"Examining the long-term spiritual effects of incentivising worship with money, and why sincerity ('Ikhlāṣ) cannot be purchased.",body:"Ṣalāh is the first of all acts of worship to be reckoned on the Day of Judgement. Its validity and acceptance hinge on 'Ikhlāṣ — sincerity, the directing of the act solely to Allah.\n\nThe Prophet ﷺ said: 'The first person to be judged on the Day of Resurrection… a man who learned knowledge and taught it, and recited the Qur'ān. He will be brought forward, and Allah will remind him of His blessings, and he will acknowledge them. He will be asked: What did you do for them? He will say: I learned knowledge and taught it, and I recited the Qur'ān for Your sake. He will be told: You lie. You did it so that it would be said: he is a scholar; and so it was said. Then it will be ordered: drag him on his face until he is cast into the Fire.' (Ṣaḥīḥ Muslim)\n\nMonetary incentivisation of Fardh Ṣalāh conditions the youth to associate worship with material reward. When the reward is withdrawn, the Ṣalāh is at risk of being abandoned. Worse, it inoculates them against the very concept of 'Ikhlāṣ.\n\nThe proper way is education, role-modelling, gentle encouragement, and the creation of an environment where Ṣalāh is the norm. This is harder, but it is the Sunnah way.\n\nSource: Ṣaḥīḥ Muslim · Iḥyā' 'Ulūm al-Dīn" },
  { title:"This 'Deen Team' Initiative — A Critical Review",cat:"akhlaq",catLabel:"Akhlāq",date:"1 Shawwāl 1446",excerpt:"A scholarly critique of a popular youth-outreach initiative whose methodology departs from established norms of Da'wah and Tarbiyah.",body:"Da'wah in Islām has a Sunnah methodology: knowledge before action, wisdom in approach, hilm (forbearance) in delivery, and adherence to the way of the Salaf al-Ṣāliḥīn.\n\nWhere a youth-outreach initiative departs from this methodology — for example, by employing entertainment as the primary vehicle, by using platforms whose dominant content is Ḥarām (music, mixing, spectacle), or by drawing youth into environments that compromise their Dīn — the methodology itself becomes a matter of concern, regardless of the stated intention.\n\nThis is not to impugn the intention of every individual involved. But methodology matters. The Prophet ﷺ did not employ the methods of the mushrikīn to call to Tawḥīd — he ﷺ used the methods of revelation.\n\nWe urge the community — and especially the youth — to seek Da'wah and Tarbiyah from established, qualified 'Ulamā, in masājid and established madāris, rather than from self-appointed outreach initiatives whose methodology departs from the Sunnah.\n\nSource: Methodology of Da'wah per classical Uṣūl works" },
  { title:"'Fiqh for Minorities' — Examining a Contemporary Trend",cat:"fiqh",catLabel:"Fiqh",date:"25 Ramaḍān 1446",excerpt:"A critical examination of the so-called 'Fiqh of Minorities' approach and its departure from established methodology in deriving rulings.",body:"'Fiqh al-Aqalliyyāt' — the so-called 'Fiqh of Minorities' — is a contemporary trend that proposes separate rulings for Muslims living as minorities in non-Muslim-majority lands, on the basis of 'maslaḥah' (public interest) and 'urf' (custom).\n\nThe established methodology of the Ummah — the four Madhāhib — already provides for the situation of Muslims in non-Muslim lands. The muftī considers maqāṣid, maṣlaḥah, 'urf, ḍarūrah, and ḥājah in the standard framework of Uṣūl al-Fiqh. There is no need for a separate 'Fiqh' for minorities.\n\nThe danger of 'Fiqh al-Aqalliyyāt' as a distinct discipline is that it becomes a vehicle for dilution — re-opening settled rulings under the banner of 'context', leading to a piecemeal collapse of the Sharī'ah in the name of accommodation.\n\nThe position of the Jamiat is that Muslims in South Africa are governed by the same Sharī'ah and the same Uṣūl as Muslims anywhere. Where genuine ḍarūrah or ḥājah arises, the muftī addresses it within the established framework.\n\nSource: Classical Uṣūl al-Fiqh · Fatāwā of contemporary Ḥanafī councils" },
  { title:"SANHA and the Standards of Ḥalāl Certification — A Community Concern",cat:"akhlaq",catLabel:"Akhlāq",date:"18 Ramaḍān 1446",excerpt:"Raising community awareness regarding concerns over certain Ḥalāl certification practices and the need for due diligence by consumers.",body:"The duty of ensuring Ḥalāl consumption rests ultimately on the consumer. A Ḥalāl certifier is an aid to fulfilling that duty — not a replacement for it. Where concerns are raised about a certifier's standards — whether in respect of stun-to-slaughter, the use of machine slaughter, the certification of establishments that serve alcohol, or transparency in financial dealings — the consumer is entitled to ask, and the certifier is duty-bound to answer.\n\nThe Jamiat's position is not to issue a blanket taḥrīm (prohibition) on any specific certifier without due process. However, the community is urged to:\n1. Educate themselves on the Shar'ī requirements of Ḥalāl slaughter.\n2. Ask questions of certifiers — transparency is a right.\n3. Support 'Ulamā-supervised slaughter where available.\n\nThe default of consumption is Taqwā — caution in matters of doubt. The Prophet ﷺ said: 'Leave what makes you doubt for what does not make you doubt.' (Sunan al-Tirmidhī, ḥasan)\n\nSource: Sunan al-Tirmidhī · Fatāwā of contemporary Ḥanafī councils" },
  { title:"An Insult to Swine: On Misapplied Comparisons in Public Discourse",cat:"akhlaq",catLabel:"Akhlāq",date:"10 Ramaḍān 1446",excerpt:"A linguistic and theological reflection on the misuse of animal comparisons in heated public discourse, and what Islamic etiquette requires.",body:"It has become common in heated discourse — including from those who claim the Da'wah — to liken those who disagree with them to swine, dogs, or other animals. This is contrary to the adab of a Muslim.\n\nThe Prophet ﷺ forbade naming a person 'mal'ūn' (accursed), and forbade reviling a Muslim with fāḥishah (fornication). He ﷺ said: 'A Muslim is the brother of a Muslim; he does not oppress him, nor does he abandon him, nor does he look down on him.' (Ṣaḥīḥ Muslim)\n\nFurthermore, the comparison itself is an insult to the animal — the animal was created by Allah in a form He chose, and the animal will be resurrected and rendered to dust, as the Qur'ān states. To liken a human — even a wrongdoer — to an animal as a term of abuse is itself a misuse of Allah's creation.\n\nThe believer is firm in the truth and gentle in speech. The Prophet ﷺ was firm with the kuffār of Makkah, but he ﷺ did not descend to abuse.\n\nSource: Ṣaḥīḥ Muslim · Sūrah al-Nisā 4:148-149 · Adab al-Dunyā wal-Dīn" },
  { title:"'Islamic' Messages With Music and Videos — A Word of Caution",cat:"akhlaq",catLabel:"Akhlāq",date:"3 Ramaḍān 1446",excerpt:"On the impermissibility of music in content branded as Islamic reminders, and guidance for sharing beneficial content without violating Sharī'ah norms.",body:"Music with instruments (other than the daff in specified contexts) is Ḥarām by the relied-upon position of the four Madhāhib. This ruling is not suspended because the content is a 'reminder' or 'Da'wah'.\n\nThe increasing trend of pairing Qur'ānic recitation, Ḥadīth, or Islamic reminders with musical tracks and elaborate video edits is a serious concern. It is not permissible to use Ḥarām means to convey a Ḥalāl message — the end does not justify the means in Sharī'ah.\n\nFor those who wish to share beneficial content:\n1. Use clean audio — no music, no instruments.\n2. Avoid images of animate life where possible — especially in 'reminder' content.\n3. Cite your sources — name the book and the number.\n4. Be wary of edits that prioritise aesthetic over content.\n\nThe Sunnah of Da'wah is clear, simple, and free of these accretions.\n\nSource: Ṣaḥīḥ al-Bukhārī (Kitāb al-Ashribah) · Fatāwā Hindiyyah" },
  { title:"The Spurious Claim That 'Coronavirus' Appears in the Qur'ān Majīd",cat:"akhlaq",catLabel:"Akhlāq",date:"24 Sha'bān 1446",excerpt:"A response to viral misinformation claiming hidden references to modern events in the text of the Qur'ān, and the correct approach to Qur'ānic interpretation.",body:"A claim circulated that 'Coronavirus' is hidden in the text of the Qur'ān by extracting letters from a verse at fixed intervals. This is a form of ta'wīl bāṭil (false interpretation) and has no basis in the methodology of Tafsīr.\n\nThe principles of Tafsīr are well-established: the Qur'ān is interpreted by the Qur'ān, then by the Sunnah, then by the statements of the Ṣaḥābah, then the Tābi'ūn, then by the Arabic language. Numerical extraction (e.g. counting forward N letters and reading the result) is not a recognised method of Tafsīr in any of the major schools.\n\nThe danger of such claims is twofold: (1) they attribute to the Qur'ān what the Qur'ān does not say, which is itself a serious matter; (2) they subject the Qur'ān to ridicule by non-Muslims when the 'prediction' is seen to be manufactured.\n\nThe correct approach is to read the Qur'ān with the 'Ulamā, follow its commands, refrain from its prohibitions, and reflect on its meanings within the established framework.\n\nSource: Muqaddimah fī Uṣūl al-Tafsīr (Ibn Taymiyyah) · al-Burhān fī 'Ulūm al-Qur'ān (Zarkashī)" },
  { title:"Distribution of Sweets After Tarāwīḥ — Sunnah or Innovation?",cat:"bidah",catLabel:"Bid'ah",date:"15 Sha'bān 1446",excerpt:"Examining the increasingly common practice of sweet distribution after Tarāwīḥ prayers and whether it carries any basis in the Sunnah.",body:"There is no dalīl — not from the Qur'ān, the Sunnah, the practice of the Ṣaḥābah, or the precedent of the Salaf — to support the regular distribution of sweets after Tarāwīḥ prayers as a religious practice.\n\nThe practice, where it has emerged, may have begun as a casual gesture but has become institutionalised in many masājid, to the point of being expected. Where something that is not from the Dīn becomes a regular, expected, communal rite attached to an 'ibādah, it carries the ruling of bid'ah.\n\nThe Prophet ﷺ said: 'Whoever introduces into this affair of ours that which is not from it, it is rejected.' (Ṣaḥīḥ al-Bukhārī & Muslim)\n\nThis does not preclude friends sharing sweets among themselves; it precludes the institutionalisation of sweet-distribution as a post-Tarāwīḥ 'tradition' that masjid committees are pressured to maintain.\n\nSource: Ṣaḥīḥ al-Bukhārī · Iqtiḍā' al-Ṣirāṭ al-Mustaqīm" },
  { title:"Illuminating the Graves — A Caution Against an Emerging Practice",cat:"bidah",catLabel:"Bid'ah",date:"6 Sha'bān 1446",excerpt:"A look at the practice of elaborate grave illumination and decoration, and how it departs from the simplicity enjoined by the Sunnah regarding graves.",body:"The Prophet ﷺ forbade the plastering of graves, building over them, sitting on them, and writing on them. (Ṣaḥīḥ Muslim)\n\nThe Sunnah of visiting graves is to greet the dead with salām, reflect on one's own mortality, and make du'ā for the deceased. The grave itself is to be simple — a mound of earth, raised a hand-span, so it is known as a grave.\n\nThe emerging practice of elaborate grave illumination — installing electric lights, building structures over graves, plastering them, erecting headstones with extensive inscriptions, and turning graveyards into places of gathering and ceremony — is contrary to the Sunnah. It also opens the door to practices that may reach the level of shirk.\n\nThe community is urged to return to the Sunnah in this matter. The deceased is not honoured by elaborate construction; he is honoured by your du'ā, your Ṣadaqah on his behalf, and your good conduct in his memory.\n\nSource: Ṣaḥīḥ Muslim · Sunan Abī Dāwūd · Fatāwā Hindiyyah" },
];

const DOWNLOADS = [
  { title:"I'tikāf: Complete Ḥanafī Guide",cat:"fiqh",catLabel:"Fiqh",meta:"PDF · 24 pages · Ḥanafī School",desc:"Comprehensive guide to the spiritual retreat — conditions, obligations, and what nullifies I'tikāf.",filename:"itikaaf-hanafi-guide.pdf" },
  { title:"Islamic Dress Code for Men & Women",cat:"fiqh",catLabel:"Dress",meta:"PDF · 18 pages",desc:"Shar'ī requirements of dress, 'awrah, and the difference between obligatory and recommended.",filename:"islamic-dress-code.pdf" },
  { title:"Bahishti Zewar (بہشتی زیور)",cat:"urdu",catLabel:"Urdu",meta:"PDF · Classic text · Urdu",desc:"The classical Ḥanafī compendium by Maulana Ashraf Ali Thanawi — an essential household text.",filename:"bahishti-zewar.pdf" },
  { title:"Zakāh Niṣāb Poster 1448 AH",cat:"zakah",catLabel:"Zakāh",meta:"PDF · Print-ready · A3/A4",desc:"Print-ready poster with current Rand values for Niṣāb, gold, silver, and Fidyah.",filename:"zakat-nisab-poster-1448.pdf" },
  { title:"Qurbāni: Complete Ruling Guide",cat:"fiqh",catLabel:"Qurbāni",meta:"PDF · 12 pages",desc:"Who Qurbāni is obligatory upon, which animals qualify, shares, and the method of slaughter.",filename:"qurbani-rulings-guide.pdf" },
  { title:"Ramaḍān Fasting & Tarāwīḥ Guide",cat:"salah",catLabel:"Ramaḍān",meta:"PDF · 30 pages",desc:"Rules of fasting, Tarāwīḥ, I'tikāf, and the Night of Power — all in one accessible booklet.",filename:"ramadan-fasting-tarawih-guide.pdf" },
  { title:"Du'ās for Qurbāni & 'Aqīqah",cat:"fiqh",catLabel:"Du'ā",meta:"PDF · 4 pages",desc:"The specific supplications to recite at the time of slaughter, with transliteration and translation.",filename:"duas-qurbani-aqiqah.pdf" },
  { title:"Satr-e-Aurah & Valid Ṣalāh Attire",cat:"salah",catLabel:"Ṣalāh",meta:"PDF · 8 pages",desc:"A concise explainer on the satr requirement for Ṣalāh and common errors in modern dress.",filename:"satr-e-aurah-salah-attire.pdf" },
  { title:"Muḥarram & Āshūrā — Sunnah Fasting Guide",cat:"salah",catLabel:"Calendar",meta:"PDF · 6 pages",desc:"The virtues and method of fasting on Āshūrā, with full Ḥadīth referencing from the Ṣiḥāḥ Sittah.",filename:"muharram-ashura-fasting-guide.pdf" },
];

const ANNOUNCEMENTS = [
  { title:"New Islamic Year 1448 AH — Muḥarram Moon Sighting",body:"Alḥamdulillāh, the new moon of Muḥarram 1448 AH has been sighted and confirmed by the Jamiatul Ulama South Africa Central Hilaal Committee. 1 Muḥarram 1448 fell on Wednesday, 17 June 2026. We wish the entire Muslim community a blessed new Islamic year. Āshūrā falls on the 10th of Muḥarram (Friday, 26 June 2026) — it is highly recommended to fast on the 9th and 10th, or the 10th and 11th.",date:"Issued by the Jamiat · Muḥarram 1448 AH",kind:"moon" },
  { title:"Financial Indicators Updated — Muḥarram 1448 AH",body:"The Zakāt Niṣāb, Mahr values, gold, silver, and Krugerrand prices have been updated for Muḥarram 1448 AH / June 2026. Please visit the Financial Indicators page for the latest figures.",date:"22 June 2026 · As at 17:00 SAST",kind:"info" },
  { title:"New Fatwa Added — I'tikāf in a Muṣallā",body:"A new ruling has been published regarding the validity of performing I'tikāf in a muṣallā (prayer room) that is not a formally designated masjid. Please consult the Fatwa Q&A section for the full response.",date:"10 June 2026",kind:"info" },
  { title:"Qurbāni Season — Dhul-Hijjah 1447",body:"Qurbāni is a confirmed Wājib upon every adult Muslim who possesses the Niṣāb amount. Please ensure your Qurbāni is completed on any of the three days of Eid. Contact us for arrangements.",date:"1 Dhul-Hijjah 1447",kind:"urgent" },
  { title:"Salāh Times — Live Board Notice",body:"Our Salāh time widget now pulls live, continuously verified times. Times are checked automatically for any changes throughout the day so you always see the current schedule.",date:"Ongoing",kind:"info" },
  { title:"Ramaḍān 1448 AH — Preparation",body:"Ramaḍān 1448 AH is approaching. The entire month of Ramaḍān is strictly compulsory fasting for every adult Muslim (29 or 30 days, depending on moon-sighting), regardless of geographic location. Begin preparation now — increase recitation of the Qur'ān, settle outstanding Ṣadaqah al-Fiṭr plans, and align your sleep and meal patterns.",date:"Upcoming",kind:"ramadan" },
];

const HADITHS = [
  { text:"The best of people are those who are most beneficial to others.", source:"Ṣaḥīḥ al-Bukhārī, Kitāb al-Muẓālam — Ḥadīth 6026 · Ṣaḥīḥ Muslim" },
  { text:"Whoever believes in Allāh and the Last Day should speak good or remain silent.", source:"Ṣaḥīḥ al-Bukhārī 6018 · Ṣaḥīḥ Muslim 47" },
  { text:"Make things easy and do not make them difficult; give glad tidings and do not scare people away.", source:"Ṣaḥīḥ al-Bukhārī 69" },
  { text:"None of you truly believes until he loves for his brother what he loves for himself.", source:"Ṣaḥīḥ al-Bukhārī 13 · Ṣaḥīḥ Muslim 45" },
  { text:"The fast of the day of Āshūrā expiates the sins of the past year.", source:"Ṣaḥīḥ Muslim 1162" },
  { text:"Actions are judged by their intentions, and every person will have what he intended.", source:"Ṣaḥīḥ al-Bukhārī 1 · Ṣaḥīḥ Muslim 1907" },
  { text:"The one who looks after a widow and a poor person is like a mujāhid in the cause of Allāh.", source:"Ṣaḥīḥ al-Bukhārī 5353 · Ṣaḥīḥ Muslim 2982" },
  { text:"The world is the prison of the believer and the paradise of the disbeliever.", source:"Ṣaḥīḥ Muslim 2956" },
  { text:"Whoever follows a path seeking knowledge, Allāh will make easy for him a path to Paradise.", source:"Ṣaḥīḥ Muslim 2699" },
  { text:"The most beloved of people to Allāh are those who are most beneficial to people.", source:"Muwaṭṭaʾ Mālik 1614 · graded ṣaḥīḥ" },
  { text:"Whoever does not show mercy to people, Allāh will not show mercy to him.", source:"Ṣaḥīḥ al-Bukhārī 7376 · Ṣaḥīḥ Muslim 2319" },
  { text:"The believer mixes with people and endures their harm; the one who does not is no true believer.", source:"Sunan Ibn Mājah 4032 · graded ḥasan" },
  { text:"Whoever guarantees me what is between his jaws and what is between his legs, I guarantee him Paradise.", source:"Ṣaḥīḥ al-Bukhārī 6474" },
  { text:"The example of the believers in their mutual love, mercy, and compassion is like one body; when one limb suffers, the whole body responds with sleeplessness and fever.", source:"Ṣaḥīḥ al-Bukhārī 6011 · Ṣaḥīḥ Muslim 2586" },
  { text:"Allāh does not look at your forms and your wealth, but He looks at your hearts and your deeds.", source:"Ṣaḥīḥ Muslim 2564" },
  { text:"The strong believer is better and more beloved to Allāh than the weak believer, though in both there is good.", source:"Ṣaḥīḥ Muslim 2664" },
  { text:"Whoever relieves a believer of a burden in this world, Allāh will relieve him of a burden on the Day of Judgement.", source:"Ṣaḥīḥ Muslim 2699" },
  { text:"The seeking of knowledge is obligatory upon every Muslim.", source:"Sunan Ibn Mājah 224 · graded ṣaḥīḥ" },
  { text:"When a person dies, his deeds end except three: continuous charity, beneficial knowledge, or a righteous child who prays for him.", source:"Ṣaḥīḥ Muslim 1631" },
  { text:"Whoever builds a masjid for Allāh, Allāh will build for him a house like it in Paradise.", source:"Ṣaḥīḥ al-Bukhārī 450 · Ṣaḥīḥ Muslim 533" },
];

const DYKS = [
  `"It is Sunnah to begin eating with Bismillāh and eat with the right hand. If one forgets, one should say: Bismillāhi awwalahu wa ākhirahu." (Sunan Abī Dāwūd 3767, Jāmiʿ al-Tirmidhī 1858 — both graded ṣaḥīḥ)`,
  `"The miswāk is Sunnah before every Ṣalāh. The Prophet ﷺ said: 'Were it not that I would cause hardship, I would have ordered the miswāk with every ablution.'" (Ṣaḥīḥ al-Bukhārī 887)`,
  `"It is recommended to recite Āyat al-Kursī after every obligatory prayer. Whoever recites it, nothing prevents him from entering Jannah except death." (Sunan al-Nasā'ī, al-Kubrā 9925; authenticated by Ibn Ḥibbān)`,
  `"The best rows in Ṣalāh for men are the first; for women, the last. The Prophet ﷺ mentioned the opposite applies to the worst rows." (Ṣaḥīḥ Muslim 440)`,
  `"Shaking hands upon meeting a Muslim brother is recommended. The Prophet ﷺ said sins fall away as leaves fall from a tree when two believers shake hands." (Sunan Abī Dāwūd 5212, Sunan Ibn Mājah 3503 — graded ḥasan)`,
  `"The Prophet ﷺ fasted on Mondays and Thursdays regularly, and when asked why, he said it was the day he was born and the day revelation came to him." (Ṣaḥīḥ Muslim 116)`,
  `"Cupping (Ḥijāmah) is most beneficial on the 17th, 19th, and 21st of the lunar month, according to the guidance of the Prophet ﷺ." (Sunan Abī Dāwūd 3861, graded ḥasan)`,
  `"Whoever says: 'Lā ilāha illā-Llāh waḥdahū lā sharīka lah, lahul-mulk wa lahul-ḥamd wa huwa 'alā kulli shay'in qadīr' — one hundred times a day will have the reward of freeing ten slaves." (Ṣaḥīḥ al-Bukhārī 3293, Ṣaḥīḥ Muslim 2691)`,
  `"The Prophet ﷺ said: 'Two words are light on the tongue, heavy on the Scale, beloved to the Most Merciful: Subḥānallāhi wa biḥamdih, Subḥānallāhil-'Aẓīm.'" (Ṣaḥīḥ al-Bukhārī 6406, Ṣaḥīḥ Muslim 2694)`,
  `"Whoever sends blessings upon me once, Allāh sends blessings upon him ten times." (Ṣaḥīḥ Muslim 408)`,
  `"Saying 'Alḥamdulillāh' fills the Scale. Saying 'Subḥānallāh' and 'Alḥamdulillāh' fill what is between the heavens and the earth." (Ṣaḥīḥ Muslim 223)`,
  `"The Prophet ﷺ said: 'Whoever eats from a plate and says: Alḥamdulillāhilladhī aṭ'amanī hādhā wa razaqanīhi min ghayri ḥawlin minnī wa lā quwwah — his past sins are forgiven.'" (Sunan al-Tirmidhī 3458, graded ḥasan)`,
];

// Masjid Al-Farooq baseline schedule
const PRAYER = [
  { name:"Fajr",    start:"06:00", end:"06:15", order:0 },
  { name:"Sunrise", start:"06:35", end:"06:35", order:1 },
  { name:"Dhuhr",   start:"13:00", end:"13:15", order:2 },
  { name:"Asr",     start:"16:30", end:"16:45", order:3 },
  { name:"Maghrib", start:"17:31", end:"17:36", order:4 },
  { name:"Isha",    start:"19:00", end:"19:15", order:5 },
];

// All 12 Hijri months — metadata for the calendar engine
const HIJRI_MONTHS = [
  { number:1,  nameLatin:"Muḥarram",        nameArabic:"مُحَرَّم",      note:"Sunnah fast on 9th & 10th (Āshūrā), or 10th & 11th. The month of the Islamic New Year." },
  { number:2,  nameLatin:"Ṣafar",            nameArabic:"صَفَر",        note:"No special Sunnah fast; the month is named for 'emptiness' (the Arabs would leave their homes empty to raid). Sūrah of the same name is not in the Qur'ān — there is no Sūrah 'Ṣafar'." },
  { number:3,  nameLatin:"Rabī' al-Awwal",   nameArabic:"رَبِيع الأَوَّل", note:"Month of the Mawlid of the Prophet ﷺ (12th). Also month of his ﷺ Hijrah to Madīnah." },
  { number:4,  nameLatin:"Rabī' al-Ākhir",   nameArabic:"رَبِيع الآخِر",  note:"Also known as Rabī' ath-Thānī. No special Sunnah fast." },
  { number:5,  nameLatin:"Jumādā al-Ūlā",    nameArabic:"جُمَادَى الأُولَى", note:"No special Sunnah fast; named for the cold season when water freezes." },
  { number:6,  nameLatin:"Jumādā al-Ākhirah",nameArabic:"جُمَادَى الآخِرَة", note:"Also known as Jumādā ath-Thāniyah. No special Sunnah fast." },
  { number:7,  nameLatin:"Rajab",            nameArabic:"رَجَب",        note:"One of the four sacred months. The Prophet ﷺ would fast in Rajab. Battle of Tabūk was prepared in Rajab 9 AH." },
  { number:8,  nameLatin:"Sha'bān",          nameArabic:"شَعْبَان",     note:"The Prophet ﷺ used to fast most of Sha'bān. The 15th night (Laylat al-Barā'ah) is significant. Ramaḍān moon-sighting begins at the end of Sha'bān." },
  { number:9,  nameLatin:"Ramaḍān",          nameArabic:"رَمَضَان",     note:"The month of Fardh fasting (29 or 30 days) for all Muslims, regardless of geography. Laylat al-Qadr (the Night of Power) is in the last ten nights, odd nights." },
  { number:10, nameLatin:"Shawwāl",          nameArabic:"شَوَّال",      note:"Eid al-Fiṭr on 1st. Fasting six days in Shawwāl is Sunnah (combined with Ramaḍān fast = fasting a lifetime, per ṣaḥīḥ ḥadīth)." },
  { number:11, nameLatin:"Dhul-Qa'dah",      nameArabic:"ذُو الْقَعْدَة",  note:"One of the four sacred months. A month of truce historically; pilgrims would head to Makkah." },
  { number:12, nameLatin:"Dhul-Ḥijjah",      nameArabic:"ذُو الْحِجَّة",   note:"The month of Ḥajj. The 10th is Eid al-Aḍḥā. Fasting the 9th (Day of 'Arafah) is Sunnah for non-pilgrims — expiates the past and coming year." },
];

async function main() {
  console.log('Clearing existing data…');
  await db.hijriMonth.deleteMany();
  await db.prayerSchedule.deleteMany();
  await db.dyk.deleteMany();
  await db.hadith.deleteMany();
  await db.announcement.deleteMany();
  await db.download.deleteMany();
  await db.fatwa.deleteMany();
  await db.article.deleteMany();

  console.log('Inserting fatwas…');
  for (const f of FATWAS) await db.fatwa.create({ data: f });

  console.log('Inserting articles…');
  for (const a of ARTICLES) await db.article.create({ data: a });

  console.log('Inserting downloads…');
  for (const d of DOWNLOADS) await db.download.create({ data: d });

  console.log('Inserting announcements…');
  for (const a of ANNOUNCEMENTS) await db.announcement.create({ data: a });

  console.log('Inserting hadiths…');
  for (const h of HADITHS) await db.hadith.create({ data: h });

  console.log('Inserting DYKs…');
  for (const d of DYKS) await db.dyk.create({ data: { text: d } });

  console.log('Inserting prayer schedule…');
  for (const p of PRAYER) await db.prayerSchedule.create({ data: p });

  console.log('Inserting Hijri months…');
  for (const m of HIJRI_MONTHS) await db.hijriMonth.create({ data: m });

  console.log('Seed complete.');
  console.log('Counts: ', {
    fatwa: await db.fatwa.count(),
    article: await db.article.count(),
    download: await db.download.count(),
    announcement: await db.announcement.count(),
    hadith: await db.hadith.count(),
    dyk: await db.dyk.count(),
    prayer: await db.prayerSchedule.count(),
    hijri: await db.hijriMonth.count(),
  });
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => db.$disconnect());
